// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3BmEv8sVQk-2Y__rVnNUgDFBOMSs2hXQ',
    appId: '1:571958404086:web:d23225f04d7c9501321dd7',
    messagingSenderId: '571958404086',
    projectId: 'mobiledevfall2024',
    authDomain: 'mobiledevfall2024.firebaseapp.com',
    storageBucket: 'mobiledevfall2024.appspot.com',
    measurementId: 'G-66SM59SEC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkxJHT84XyCNcCoy27qGRLnuD11CK4PPE',
    appId: '1:571958404086:android:6623bdd8f82c9382321dd7',
    messagingSenderId: '571958404086',
    projectId: 'mobiledevfall2024',
    storageBucket: 'mobiledevfall2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL7P0kVVvGpHwXPMWCfqjWAEZewsAGgkc',
    appId: '1:571958404086:ios:a5c61e2a0304a54e321dd7',
    messagingSenderId: '571958404086',
    projectId: 'mobiledevfall2024',
    storageBucket: 'mobiledevfall2024.appspot.com',
    iosBundleId: 'com.example.project1MobdevAhmad917607485',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL7P0kVVvGpHwXPMWCfqjWAEZewsAGgkc',
    appId: '1:571958404086:ios:a5c61e2a0304a54e321dd7',
    messagingSenderId: '571958404086',
    projectId: 'mobiledevfall2024',
    storageBucket: 'mobiledevfall2024.appspot.com',
    iosBundleId: 'com.example.project1MobdevAhmad917607485',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3BmEv8sVQk-2Y__rVnNUgDFBOMSs2hXQ',
    appId: '1:571958404086:web:c625080e27840659321dd7',
    messagingSenderId: '571958404086',
    projectId: 'mobiledevfall2024',
    authDomain: 'mobiledevfall2024.firebaseapp.com',
    storageBucket: 'mobiledevfall2024.appspot.com',
    measurementId: 'G-1DFG21XKGZ',
  );
}
